# Generated by Django 3.0.3 on 2020-02-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=40)),
                ('invoiceNumber', models.IntegerField()),
                ('invoiceDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unitAmount', models.IntegerField()),
            ],
        ),
    ]
