# Generated by Django 3.0.3 on 2020-02-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_inventory', models.FileField(upload_to='invoice/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_app.Invoice')),
            ],
        ),
    ]
