# Generated by Django 3.0.3 on 2020-02-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_invoicefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicefile',
            old_name='invoice_inventory',
            new_name='invoice_csv',
        ),
    ]
