# Generated by Django 3.0.3 on 2020-02-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0003_auto_20200206_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.DateField(verbose_name=['%Y-%m-%d']),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceDate',
            field=models.DateField(verbose_name=['%Y-%m-%d']),
        ),
    ]
