# Generated by Django 3.0.3 on 2020-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0005_auto_20200206_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicefile',
            old_name='invoice_csv',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='invoicefile',
            name='invoice',
        ),
    ]
